### ISSUE TITLE
Naming Problem - "Other Repo PR'S"

### ISSUE THREAD

**Issue by kabirbaidhya** [leapfrogtechnology/frogtoberfest#40]
**Current behavior:**
We agree that we've tried but still couldn't figure out a better name for "Other Repo PR'Ss". 

Feel free to propose if you have any and let's discuss :sweat_smile:.
![image](https://user-images.githubusercontent.com/3315763/67623792-247d4000-f849-11e9-8588-3e6dcff11d33.png)

**Expected behavior:**
Not sure - Need to figure out / discuss. 

**Proposal:**
How about taking an infographic approach for displaying this data? Eg: a pie chart, bar chart? 
And additionally we can have some details below them to explain our criteria like this:
    
    **Criteria**
    Total Pull Requests = 10 / 10 (100% Complete)
    Pull Requests for Others = 2 / 4 (50% Complete)

Perhaps this is a food for thought and a good discussion to have with our design experts? 
cc @mesaugat @sagunji @nishanbajracharya

**Comment by nishanbajracharya** [comment]
@kabirbaidhya I agree. We could just say `Forked Repo PRs` but that also doesn't quite sound right. A better wording for `someone else's repo` would be more appropriate. 

The infographic idea seems nice but the raw `5/10 PRs` information is more important to highlight. In the end, a person trying to figure out their progress would care more about how many PRs to go rather than what percentage is left. I'd suggest keeping the existing visualization (ie raw numbers) and having any form of infographic as a visual toggle option.

**Comment by kabirbaidhya** [comment]
Yes, that's true. Numbers are the thing for the users - we can't remove that. 

But I still think there could be some kind of visual tweak we can do more from a UX perspective - perhaps having something like "**PRs for Others**" and showing a detail information on what that means on a tooltip on hover like - "You have done 3 / 4 of your pull requests on other's repositories.".
